### ISSUE TITLE
Bug: SSO'd users have no name in Superset

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-superset#11]
Superset uses the "first name" and "last name" fields to display initials for owners / creators of charts and dashboards etc. Right now those fields aren't populated from SSO, so it's just a blank circle. Low priority, but it would be cool if we could populate those, even if it's just with the username.

![Screenshot 2023-03-22 at 2 06 52 PM](https://user-images.githubusercontent.com/112640379/226997785-c6fa1158-10ea-46f1-bd4a-d723d56c37a9.png)

**Comment by bmtcril** [comment]
This is likely a thing we can resolve along with https://github.com/openedx/openedx-oars/issues/42

**Comment by Ian2012** [comment]
assign me
