### ISSUE TITLE
Superset production configuration and testing

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-superset#15]
There are a number of production use cases and configurations that we need to test and fix where broken. This issue is to track all of those, and they can be broken out into separate issues if the size of the work warrants it. Right now this is just collecting things in one place.

- [x] Test against ClickHouse Cloud
- [x] Test against ClickHouse SSL
- [x] Test Superset SSL configuration 
- [x] Make a production ready k8s configuration
- [x] Test K8s, including Superset running from a different namespace than other services
- [x] Pin image versions
- [x] Run a security pass on Superset packages versions, image, and configuration

**Comment by Ian2012** [comment]
The following tasks were performed:

- Test Superset SSL configuration
- Make a production ready k8s configuration
- Pin image versions

**Comment by bmtcril** [comment]
Thanks @Ian2012 , I've updated the ticket. I also created a new issue for the SSL bug mentioned above: #30

**Comment by bmtcril** [comment]
The list of known v1 blocking issues should be everything labeled "oars v1": https://github.com/search?q=org%3Aopenedx+label%3A%22oars+v1%22++++&type=issues&state=open

If you run across anything missing the label let me know or use the Github comment-to-label action: `label: oars v1`

**Comment by Ian2012** [comment]
@bmtcril can this be closed?

**Comment by bmtcril** [comment]
I think so, we'll need another round of testing everything once the projects are consolidated but that's a whole other ticket
