### ISSUE TITLE
Superset - Sentry integration

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-superset#16]
Is there interest to integrate sentry as part of the superset plugin?

It can be installed with something similar to this:

https://github.com/onaio/ansible-superset/blob/master/templates/superset_python_path/superset_config.py.j2#L204-L213

**Comment by Ian2012** [comment]
cc @bmtcril

**Comment by bmtcril** [comment]
I'm not against if if that's a service that operators use, but it doesn't seem like it's being used in very many places across the platform. I'm only seeing it in `openedx-webhooks`, in a quick search.
