### ISSUE TITLE
Add Talisman security headers

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-superset#21]
Superset is set up for Flask Talisman for some headers-based security enhancements: https://openbase.com/python/flask-talisman

We should make a configurable CSP with sensible defaults based on their docs here: https://superset.apache.org/docs/security/#content-security-policy-csp and I think that it will "just work".

**Comment by Ian2012** [comment]
Would be valid to use the superset basic default?

I guess a setting should hold this value:

```python
TALISMAN_CONFIG = {
    "content_security_policy": {
        "default-src": ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
        "img-src": ["'self'", "data:"],
        "worker-src": ["'self'", "blob:"],
        "connect-src": ["'self'", "https://api.mapbox.com", "https://events.mapbox.com"],
        "object-src": "'none'",
    }
}
```

Keep in mind that those are the minimum values that superset needs to work correctly. Site operators should be able to adjust it to it's needs.

**Comment by Ian2012** [comment]
@bmtcril ready https://github.com/openedx/tutor-contrib-superset/pull/35

**Comment by Ian2012** [comment]
This can be closed too
