### ISSUE TITLE
When running on HTTPS the sso doesn't work due to redirect URL

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-superset#30]
When running on HTTPS the sso doesn't work because the redirect uri is taken as http:{{LMS_HOST}}/...

Any ideas?

Checking the application configuration shows the correct information:

![image](https://user-images.githubusercontent.com/33465240/233203237-c9aefcc9-f7a7-4e4e-8c96-81448045208f.png)

![image](https://user-images.githubusercontent.com/33465240/233203430-829aea57-dd89-4dd0-a8e4-f741f3382037.png)

_Originally posted by @Ian2012 in https://github.com/openedx/tutor-contrib-superset/issues/15#issuecomment-1515399257_

**Comment by mariajgrimaldi** [comment]
I did some digging in the Flask-AppBuilder and found the redirect URI parameter is generated [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/8a17103d0c2ad4ee2bb4234077306465bd239672/flask_appbuilder/security/views.py#L640) using a function called `url_for` defined by flask itself. Take in mind one of the parameters is `_external=True`. Now, the url_for docs say:

> In some cases, such as email messages, you want URLs to include the scheme and domain, like https://example.com/hello. When not in an active request, URLs will be external by default, but this requires setting [SERVER_NAME](https://flask.palletsprojects.com/en/2.3.x/config/#SERVER_NAME) so Flask knows what domain to use. [APPLICATION_ROOT](https://flask.palletsprojects.com/en/2.3.x/config/#APPLICATION_ROOT) and [PREFERRED_URL_SCHEME](https://flask.palletsprojects.com/en/2.3.x/config/#PREFERRED_URL_SCHEME) should also be configured as needed. 

https://flask.palletsprojects.com/en/2.3.x/api/#flask.Flask.url_for

Should we configure PREFERRED_URL_SCHEME (HTTP by default) for our superset application? I haven't tested or even know if this is the right path. I could try it later though.

**Comment by bmtcril** [comment]
@mariajgrimaldi thanks for digging into this, that seems like a good place to start!

**Comment by mariajgrimaldi** [comment]
I found this:
```
k exec -it pod/superset-7955b5465-bzxqq -- bash
flask shell
>>> app.config["PREFERRED_URL_SCHEME"]
'http'
```
So that might be the reason. I haven't figured out how to configure it differently though 🦀

**Comment by mariajgrimaldi** [comment]
Useful references:
https://github.com/dpgaspar/Flask-AppBuilder/issues/1666
https://github.com/apache/airflow/issues/17536#issuecomment-900343494
https://github.com/apache/superset/pull/8117

**Comment by mariajgrimaldi** [comment]
We figured that this config `PREFERRED_URL_SCHEME` is used when there is not a request context which there is in our case. So that wasn't the solution. After some digging, we found the issues I mentioned above. After trying some stuff out we managed to make it work with this:
https://github.com/apache/superset/blob/master/superset/config.py#L273-L277
```
# tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py
ENABLE_PROXY_FIX = True
FEATURE_FLAGS = {
    "DYNAMIC_PLUGINS": True
}
```
So we should add that config when using https!

**Comment by bmtcril** [comment]
Great, I look forward to hearing how it goes!

**Comment by mariajgrimaldi** [comment]
We have a fix! I already linked the PR.

**Comment by mariajgrimaldi** [comment]
assign me

**Comment by Ian2012** [comment]
@bmtcril this one is resolved
